### ISSUE TITLE
link an new repo is broken

### ISSUE THREAD

**Issue by firexx** [Ultimaker/CuraSolidWorksPlugin#28]
This is legacy software, an old version that is no longer maintained. Please refer to [the new repository](https://github.com/thopiekar/CuraSolidWorksPlugin).

link opens 404 error site

**Comment by jellespijker** [comment]
is you rightly noticed, this is a legacy project, unfortunately the links points towards an url for a plugin from a community developer which is also not longer maintained.

Closing this issue as won't fix
