### ISSUE TITLE
Feature: Adding optimized export profile for desktop 3D printing

### ISSUE THREAD

**Issue by thopiekar** [Ultimaker/CuraSolidWorksPlugin#9]
It needs to be investigated, whether the fine setting of SolidWorks is really fine enough.
We don't know from Dessault Systems itself, how they defined fine. How have decisions been made to call it "fine"?
Based on FDM, SLS or even SLA printing?!

**Comment by thopiekar** [comment]
Good point, but I doubt it is easy to implement. But what we can do instead is comparing the extruded volumina with the modeled volumina. If there is a discrepancy, then we should trigger an error.

**Comment by Ghostkeeper** [comment]
Inspired by this idea I've just been making a rather interesting OpenSCAD script that implements this. Nothing that's good for release but rather interesting:

    line_width = 0.4;
    layer_height = 0.1;

    module originalShape() {
        cube(10);
        cube([20, 0.1, 10]);
        cube([0.1, 20, 10]);
        cube([20, 20, 0.01]);
        /*scale([0.1, 1, 1])
            cylinder(r=10, $fn=3, h=5);*/
    }

    //Shape to sum thin pieces with.
    module sumShape()
        scale([line_width / 2, line_width / 2, layer_height / 2])
            translate([0, 0, -0.5])
                cylinder(r=1, h=1, $fn=30);

    minkowski() { //Make the thin pieces thicker.
        difference() { //Find the thin pieces by subtracting an inset of the original from the original.
            originalShape();
            minkowski() {
                difference() { //Perform an inset ("Minkowski subtraction")
                    originalShape();
                    minkowski() {
                        difference() { //A negative of the original (mould).
                            minkowski() {
                                hull() originalShape();
                                sumShape();
                            }
                            originalShape();
                        }
                        sumShape();
                    }
                }
                //Double scale gets rid of thin pieces that are attached to thick pieces.
                //Since those pieces are within 1 radius of the model anyway, all volume
                //offset we do on them will either be inside the thick piece or superfluous.
                scale(2)
                    sumShape();
            }
        }
        sumShape();
    }
    originalShape(); //The normal (non-thin) pieces.
